# Generated by Django 3.2.8 on 2021-10-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow_Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_yaml', models.TextField()),
                ('workflow_custform', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='Date published')),
            ],
        ),
    ]
