# Generated by Django 3.2.8 on 2021-10-10 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_forms', '0004_alter_workflow_template_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploaded_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=512, null=True)),
                ('uid', models.UUIDField()),
                ('uploaded_file', models.FileField(upload_to='ac490e2d-d358-4f16-b892-e3c8cc63b035/6356fccd-0789-4dd8-a757-fb9d845940b8')),
            ],
        ),
    ]
